{
 "title": "Query Performance Metrics",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "Average Queries per Second for the interval",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(indexer_service_queries_ok[1m]))",
     "legendFormat": "OK"
    },
    {
     "expr": "sum(rate(indexer_service_queries_failed[1m]))",
     "legendFormat": "FAIL"
    }
   ]
  },
  {
   "title": "Queries Failed vs OK over time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(indexer_service_queries_failed)",
     "legendFormat": "Failed"
    },
    {
     "expr": "sum(indexer_service_queries_ok)",
     "legendFormat": "OK"
    }
   ]
  },
  {
   "title": "Queries Failed vs OK per second",
   "type": "graph",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "sum(rate(indexer_service_queries_failed[10s]))",
     "legendFormat": "Failed"
    },
    {
     "expr": "sum(rate(indexer_service_queries_ok[10s]))",
     "legendFormat": "OK"
    }
   ]
  },
  {
   "title": "Total queries by subgraph per second",
   "type": "graph",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "sum by (deployment) (rate(indexer_service_queries_total[10s]))",
     "legendFormat": "{{deployment}}"
    }
   ]
  },
  {
   "title": "Total queries per deployment since last restart",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "sort_desc(sum by (deployment) (indexer_service_queries_total))",
     "legendFormat": "{{ deployment }}"
    }
   ]
  },
  {
   "title": "Indexer / Total errors count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    { "expr": "indexer_error", "legendFormat": "{{code}}  /  {{job}}" }
   ]
  },
  {
   "title": "Channel Messages Failed vs OK over time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(indexer_service_channel_messages_failed)",
     "legendFormat": "Failed"
    },
    {
     "expr": "sum(indexer_service_channel_messages_ok)",
     "legendFormat": "OK"
    }
   ]
  },
  {
   "title": "Indexer errors (over 5 minutes, by code)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(indexer_error[30s])) by (code)",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "Total Channel Messages by Servicenode per second [stacked]",
   "type": "graph",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(indexer_service_channel_messages_total[10s])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Channel Messages Failed vs OK per second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(indexer_service_channel_messages_failed[1m]))",
     "legendFormat": "Failed"
    },
    {
     "expr": "sum(rate(indexer_service_channel_messages_ok[1m]))",
     "legendFormat": "OK"
    }
   ]
  },
  {
   "title": "Cost Model Queries over time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(indexer_service_cost_model_queries_invalid)",
     "legendFormat": "queries_invalid"
    },
    {
     "expr": "sum(indexer_service_cost_model_batch_queries)",
     "legendFormat": "batch queries"
    },
    {
     "expr": "sum(indexer_service_cost_model_batch_queries_failed)",
     "legendFormat": "batch queries_failed"
    },
    {
     "expr": "sum(indexer_service_cost_model_batch_queries_invalid)",
     "legendFormat": "batch  queries_invalid"
    }
   ]
  },
  {
   "title": "Total Cost Model Batch Queries by Servicenode per second",
   "type": "graph",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 51 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(indexer_service_cost_model_batch_queries[10s])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Cost Model Queries per second",
   "type": "graph",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(indexer_service_cost_model_queries_invalid[1m]))",
     "legendFormat": "queries_invalid"
    },
    {
     "expr": "sum(rate(indexer_service_cost_model_batch_queries[1m]))",
     "legendFormat": "batch queries"
    },
    {
     "expr": "sum(rate(indexer_service_cost_model_batch_queries_failed[1m]))",
     "legendFormat": "batch queries_failed"
    },
    {
     "expr": "sum(rate(indexer_service_cost_model_batch_queries_invalid[1m]))",
     "legendFormat": "batch  queries_invalid"
    }
   ]
  }
 ]
}